// Main exports

// Re-export commonly used AI SDK types for convenience
// This allows consumers to import everything from bashkit without
// needing to also import from "ai" for types used in return values
export type {
  UIMessageStreamWriter,
  StreamTextResult,
  Tool,
  ToolSet,
  LanguageModel,
  LanguageModelMiddleware,
  Output,
} from "ai";

// Middleware
export {
  anthropicPromptCacheMiddleware,
  anthropicPromptCacheMiddlewareV2,
} from "./middleware";
export type {
  E2BSandboxConfig,
  LocalSandboxConfig,
  VercelSandboxConfig,
} from "./sandbox";
// Sandbox factories
export {
  createE2BSandbox,
  createLocalSandbox,
  createVercelSandbox,
  ensureSandboxTools,
} from "./sandbox";

// Subagent foundation
export type {
  JsonObject,
  JsonPrimitive,
  JsonValue,
  ResolvedSubagentProfile,
  ResolvedSubagentRunRequest,
  SubagentCodemodePolicy,
  SubagentContextPolicy,
  SubagentContextPolicyInput,
  SubagentController,
  SubagentControllerConfig,
  SubagentCostPolicy,
  SubagentCostPolicyInput,
  SubagentError,
  SubagentEvent,
  SubagentEventSink,
  SubagentEventType,
  SubagentFollowupRequest,
  SubagentHandle,
  SubagentId,
  SubagentInterruptRequest,
  SubagentInterruptResult,
  SubagentLifecycleHooks,
  SubagentListFilter,
  SubagentMailboxMessage,
  SubagentMessageRequest,
  SubagentMessageResult,
  SubagentMetadata,
  SubagentMetadataPatch,
  SubagentPath,
  SubagentPolicyState,
  SubagentProfileDefaults,
  SubagentProfileInput,
  SubagentProfileRegistry,
  SubagentRecord,
  SubagentRegistry,
  SubagentReservationRequest,
  SubagentRunResult,
  SubagentRunner,
  SubagentRunnerCallbacks,
  SubagentRunnerCapabilities,
  SubagentSpawnRequest,
  SubagentSpawnResult,
  SubagentStatus,
  SubagentStore,
  SubagentUsage,
  SubagentWaitRequest,
  SubagentWaitResult,
} from "./subagents";
export {
  DEFAULT_SUBAGENT_CODEMODE_POLICY,
  DEFAULT_SUBAGENT_CONTEXT_POLICY,
  DEFAULT_SUBAGENT_COST_POLICY,
  DEFAULT_SUBAGENT_PROFILE_NAME,
  checkSubagentCostPolicy,
  checkSubagentExecutionLimits,
  clampSubagentWaitTimeout,
  createInMemorySubagentStore,
  createMailboxMessage,
  createMemorySubagentEventSink,
  createStaticSubagentRunner,
  createSubagentController,
  createSubagentId,
  createSubagentProfileRegistry,
  createSubagentRegistry,
  describeSubagentProfile,
  emitSubagentEvent,
  filterSubagentTools,
  isActiveSubagentStatus,
  isTerminalSubagentStatus,
  normalizeSubagentPath,
  resetSubagentIdCounterForTests,
  resolveSubagentContextPolicy,
  resolveSubagentCostPolicy,
  resolveSubagentPath,
} from "./subagents";

// Runtime events, plans, approvals, and host-facing snapshots
export type {
  AgentActivitySnapshot,
  AgentLifecycleEvent,
  AgentStatus,
  ApprovalDecision,
  ApprovalRequest,
  ApprovalRequestedEvent,
  ApprovalResolvedEvent,
  ApprovalResult,
  ApprovalSubject,
  ChangesSnapshotItem,
  CommandOutputEvent,
  CostUpdatedEvent,
  FileChangedEvent,
  FileChangeKind,
  MemoryRuntimeEventSink,
  PlanItem,
  PlanItemStatus,
  PlanSnapshot,
  PlanState,
  PlanStats,
  PlanUpdateContext,
  PlanUpdateError,
  PlanUpdateInput,
  PlanUpdateResult,
  PlanUpdatedEvent,
  ProgressSnapshot,
  RuntimeEvent,
  RuntimeEventBase,
  RuntimeEventListener,
  RuntimeEventSink,
  RuntimeEventType,
  RuntimeUsage,
  ThreadStartedEvent,
  ToolCompletedEvent,
  ToolFailedEvent,
  ToolStartedEvent,
  TurnCompletedEvent,
  TurnFailedEvent,
  TurnStartedEvent,
} from "./runtime";
export {
  createApprovalId,
  createApprovalRequest,
  createApprovalRequestedEvent,
  createApprovalResolvedEvent,
  createApprovalResult,
  createMemoryRuntimeEventSink,
  createPlanState,
  createPlanUpdatedEvent,
  createRuntimeEvent,
  emitRuntimeEvent,
  getPlanStats,
  projectAgentActivitySnapshot,
  projectChangesSnapshot,
  projectPlanSnapshot,
  projectProgressSnapshot,
  resetApprovalIdCounterForTests,
  snapshotPlanState,
  updatePlanState,
  validatePlanUpdate,
} from "./runtime";

// Sandbox interface
export type { ExecOptions, ExecResult, Sandbox } from "./sandbox/interface";
// Tool output types
export type {
  // Result type from createAgentTools
  AgentToolsResult,
  // AskUser tool
  AskUserAnswers,
  AskUserInput,
  AskUserOutput,
  AskUserQuestion,
  AskUserQuestionOption,
  AskUserToolConfig,
  // Sandbox tools
  BashError,
  BashOutput,
  CodemodeConfig,
  CodemodeConnectorBinding,
  CodemodeExecuteOptions,
  CodemodeExecuteResult,
  CodemodeExecutor,
  CodemodeResolvedProvider,
  CodemodeToolProvider,
  CodemodeToolExclusionReason,
  CreateCodeTool,
  EditError,
  EditOutput,
  // Plan mode tools
  EnterPlanModeError,
  EnterPlanModeOutput,
  ExitPlanModeError,
  ExitPlanModeOutput,
  PlanModeState,
  GlobError,
  GlobOutput,
  PatchError,
  PatchFileResult,
  PatchOutput,
  CompactSubagentRecord,
  InterruptAgentOutput,
  ListAgentsOutput,
  MessageAgentOutput,
  SpawnAgentOutput,
  SubagentControlToolConfig,
  SubagentToolError,
  WaitAgentOutput,
  GrepContentOutput,
  GrepCountOutput,
  GrepError,
  GrepFilesOutput,
  GrepMatch,
  GrepOutput,
  ReadDirectoryOutput,
  ReadError,
  ReadOutput,
  ReadTextOutput,
  // Skill tool
  SkillError,
  SkillOutput,
  SkillToolConfig,
  // Task tool
  SubagentEventData,
  SubagentStepEvent,
  SubagentTypeConfig,
  TaskError,
  TaskOutput,
  TaskToolConfig,
  // UpdatePlan tool
  UpdatePlanError,
  UpdatePlanOutput,
  UpdatePlanToolConfig,
  // TodoWrite tool
  TodoItem,
  TodoState,
  TodoWriteError,
  TodoWriteOutput,
  // Web tools
  WebFetchError,
  WebFetchOutput,
  WebSearchError,
  WebSearchOutput,
  WebSearchResult,
  WriteError,
  WriteOutput,
} from "./tools";
// Tool factories
export {
  createAgentTools,
  createAskUserTool,
  createBashTool,
  createCodemodeTool,
  createEditTool,
  createEnterPlanModeTool,
  createExitPlanModeTool,
  createGlobTool,
  createGrepTool,
  createPatchTool,
  createFollowupTaskTool,
  createInterruptAgentTool,
  createListAgentsTool,
  createReadTool,
  createSendMessageTool,
  createSkillTool,
  createSpawnAgentTool,
  createSubagentControlTools,
  createTaskTool,
  createTodoWriteTool,
  createUpdatePlanTool,
  createWaitAgentTool,
  createWebFetchTool,
  createWebSearchTool,
  createWriteTool,
  selectCodemodeTools,
} from "./tools";
// Configuration types
export type {
  AgentConfig,
  AskUserConfig,
  BudgetConfig,
  CacheConfig,
  ContextConfig,
  ModelRegistryConfig,
  ModelRegistryProvider,
  PricingProvider,
  RuntimeConfig,
  SkillConfig,
  ToolConfig,
  WebFetchConfig,
  WebSearchConfig,
} from "./types";
export { DEFAULT_CONFIG } from "./types";

// Context layer (tool execution gating + output policy + prompt assembly)
export type {
  ContextLayer,
  ExecutionPolicyConfig,
  OutputPolicyConfig,
  StashOutputConfig,
  InstructionDiscoveryConfig,
  DiscoveredInstructions,
  EnvironmentContext,
  EnvironmentContextConfig,
  ToolGuidanceConfig,
  SystemContextConfig,
  SystemContext,
  PrepareStepConfig,
} from "./context";
export {
  withContext,
  applyContextLayers,
  createExecutionPolicy,
  createOutputPolicy,
  discoverInstructions,
  collectEnvironment,
  formatEnvironment,
  buildToolGuidance,
  buildSystemContext,
  createPrepareStep,
} from "./context";

// Cache utilities
export type {
  CachedTool,
  CacheEntry,
  CacheOptions,
  CacheStats,
  CacheStore,
  RedisCacheStoreOptions,
  RedisClient,
} from "./cache";
export { cached, createRedisCacheStore, LRUCacheStore } from "./cache";
export type {
  BudgetStatus,
  BudgetTracker,
  ModelInfo,
  ModelPricing,
  CompactConversationConfig,
  CompactConversationResult,
  CompactConversationState,
  ContextMetrics,
  ContextStatus,
  ContextStatusConfig,
  ContextStatusLevel,
  DebugEvent,
  ModelContextLimit,
  PruneMessagesConfig,
} from "./utils";
// Utils
export {
  createBudgetTracker,
  fetchOpenRouterModels,
  getModelContextLength,
  clearDebugLogs,
  CompactionError,
  compactConversation,
  contextNeedsAttention,
  contextNeedsCompaction,
  createAutoCompaction,
  createCompactConfig,
  createCompactConfigFromModels,
  estimateMessagesTokens,
  estimateMessageTokens,
  estimateTokens,
  getContextStatus,
  getDebugLogs,
  isDebugEnabled,
  MODEL_CONTEXT_LIMITS,
  pruneMessagesByTokens,
  reinitDebugMode,
} from "./utils";

// Skills (Agent Skills standard support)
export type {
  DiscoverSkillsOptions,
  SkillBundle,
  SkillMetadata,
} from "./skills";
export {
  discoverSkills,
  fetchSkill,
  fetchSkills,
  loadSkillBundle,
  loadSkillBundles,
  parseSkillMetadata,
  skillsToXml,
} from "./skills";

// Setup (Agent environment setup for sandboxes)
export type {
  AgentEnvironmentConfig,
  SetupResult,
  SkillContent,
} from "./setup";
export { setupAgentEnvironment } from "./setup";
